spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
